// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Activefqdnlists activefqdnlists
//
// swagger:model activefqdnlists
type Activefqdnlists struct {

	// fqdnlistnames
	// Required: true
	Fqdnlistnames []Fqdnlistname `json:"fqdnlistnames"`

	// id
	// Read Only: true
	// Min Length: 1
	// Format: ObjectId
	ID *strfmt.ObjectId `json:"id,omitempty" bson:"_id, omitempty"`

	// time
	Time int64 `json:"time,omitempty"`
}

// Validate validates this activefqdnlists
func (m *Activefqdnlists) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFqdnlistnames(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Activefqdnlists) validateFqdnlistnames(formats strfmt.Registry) error {

	if err := validate.Required("fqdnlistnames", "body", m.Fqdnlistnames); err != nil {
		return err
	}

	for i := 0; i < len(m.Fqdnlistnames); i++ {

		if err := m.Fqdnlistnames[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fqdnlistnames" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("fqdnlistnames" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *Activefqdnlists) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", m.ID.String(), 1); err != nil {
		return err
	}

	if err := validate.FormatOf("id", "body", "ObjectId", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this activefqdnlists based on the context it is used
func (m *Activefqdnlists) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFqdnlistnames(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Activefqdnlists) contextValidateFqdnlistnames(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Fqdnlistnames); i++ {

		if err := m.Fqdnlistnames[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fqdnlistnames" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("fqdnlistnames" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *Activefqdnlists) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Activefqdnlists) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Activefqdnlists) UnmarshalBinary(b []byte) error {
	var res Activefqdnlists
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
