// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostservicePath arc costservice path
//
// swagger:model arc_costservice_path
type ArcCostservicePath struct {

	// path
	Path string `json:"path,omitempty"`

	// total cost
	TotalCost float64 `json:"totalCost,omitempty"`
}

// Validate validates this arc costservice path
func (m *ArcCostservicePath) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc costservice path based on context it is used
func (m *ArcCostservicePath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostservicePath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostservicePath) UnmarshalBinary(b []byte) error {
	var res ArcCostservicePath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
