// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostServiceLinkdata arc cost service linkdata
//
// swagger:model arc_cost_service_linkdata
type ArcCostServiceLinkdata struct {

	// atobcost
	Atobcost float64 `json:"atobcost,omitempty"`

	// btoacost
	Btoacost float64 `json:"btoacost,omitempty"`

	// vertex a
	VertexA *ArcCostserviceVertex `json:"vertexA,omitempty"`

	// vertex b
	VertexB *ArcCostserviceVertex `json:"vertexB,omitempty"`
}

// Validate validates this arc cost service linkdata
func (m *ArcCostServiceLinkdata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVertexA(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVertexB(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostServiceLinkdata) validateVertexA(formats strfmt.Registry) error {
	if swag.IsZero(m.VertexA) { // not required
		return nil
	}

	if m.VertexA != nil {
		if err := m.VertexA.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vertexA")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vertexA")
			}
			return err
		}
	}

	return nil
}

func (m *ArcCostServiceLinkdata) validateVertexB(formats strfmt.Registry) error {
	if swag.IsZero(m.VertexB) { // not required
		return nil
	}

	if m.VertexB != nil {
		if err := m.VertexB.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vertexB")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vertexB")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this arc cost service linkdata based on the context it is used
func (m *ArcCostServiceLinkdata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVertexA(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVertexB(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostServiceLinkdata) contextValidateVertexA(ctx context.Context, formats strfmt.Registry) error {

	if m.VertexA != nil {
		if err := m.VertexA.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vertexA")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vertexA")
			}
			return err
		}
	}

	return nil
}

func (m *ArcCostServiceLinkdata) contextValidateVertexB(ctx context.Context, formats strfmt.Registry) error {

	if m.VertexB != nil {
		if err := m.VertexB.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vertexB")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vertexB")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostServiceLinkdata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostServiceLinkdata) UnmarshalBinary(b []byte) error {
	var res ArcCostServiceLinkdata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
