// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostInput arc cost input
//
// swagger:model arc_cost_input
type ArcCostInput struct {

	// deployment name
	DeploymentName string `json:"deploymentName,omitempty"`

	// destination cloud provider
	DestinationCloudProvider string `json:"destinationCloudProvider,omitempty"`

	// destination region
	DestinationRegion string `json:"destinationRegion,omitempty"`

	// duration in hrs
	DurationInHrs int64 `json:"durationInHrs,omitempty"`

	// instance type
	InstanceType string `json:"instanceType,omitempty"`

	// interface names
	InterfaceNames []string `json:"interfaceNames"`

	// max hops
	MaxHops int64 `json:"maxHops,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// region
	Region string `json:"region,omitempty"`
}

// Validate validates this arc cost input
func (m *ArcCostInput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc cost input based on context it is used
func (m *ArcCostInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostInput) UnmarshalBinary(b []byte) error {
	var res ArcCostInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
