// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostProviderRegionDetail arc cost provider region detail
//
// swagger:model arc_cost_provider_region_detail
type ArcCostProviderRegionDetail struct {

	// region code
	RegionCode string `json:"RegionCode,omitempty"`

	// region name
	RegionName string `json:"RegionName,omitempty"`

	// standard internet egress
	StandardInternetEgress []*ArcCostStandardInternetEgress `json:"StandardInternetEgress"`
}

// Validate validates this arc cost provider region detail
func (m *ArcCostProviderRegionDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStandardInternetEgress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostProviderRegionDetail) validateStandardInternetEgress(formats strfmt.Registry) error {
	if swag.IsZero(m.StandardInternetEgress) { // not required
		return nil
	}

	for i := 0; i < len(m.StandardInternetEgress); i++ {
		if swag.IsZero(m.StandardInternetEgress[i]) { // not required
			continue
		}

		if m.StandardInternetEgress[i] != nil {
			if err := m.StandardInternetEgress[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("StandardInternetEgress" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("StandardInternetEgress" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this arc cost provider region detail based on the context it is used
func (m *ArcCostProviderRegionDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStandardInternetEgress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostProviderRegionDetail) contextValidateStandardInternetEgress(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.StandardInternetEgress); i++ {

		if m.StandardInternetEgress[i] != nil {
			if err := m.StandardInternetEgress[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("StandardInternetEgress" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("StandardInternetEgress" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostProviderRegionDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostProviderRegionDetail) UnmarshalBinary(b []byte) error {
	var res ArcCostProviderRegionDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
