// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostOctetsInfo arc cost octets info
//
// swagger:model arc_cost_octets_info
type ArcCostOctetsInfo struct {

	// delta in octets
	DeltaInOctets float64 `json:"deltaInOctets,omitempty"`

	// delta out octets
	DeltaOutOctets float64 `json:"deltaOutOctets,omitempty"`

	// in octets
	InOctets float64 `json:"inOctets,omitempty"`

	// out octets
	OutOctets float64 `json:"outOctets,omitempty"`
}

// Validate validates this arc cost octets info
func (m *ArcCostOctetsInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc cost octets info based on context it is used
func (m *ArcCostOctetsInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostOctetsInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostOctetsInfo) UnmarshalBinary(b []byte) error {
	var res ArcCostOctetsInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
