// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostInstanceInfo arc cost instance info
//
// swagger:model arc_cost_instance_info
type ArcCostInstanceInfo struct {

	// begin range
	BeginRange string `json:"beginRange,omitempty"`

	// end range
	EndRange string `json:"endRange,omitempty"`

	// error
	Error string `json:"error,omitempty"`

	// memory
	Memory string `json:"memory,omitempty"`

	// price per unit
	PricePerUnit string `json:"pricePerUnit,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`

	// v CPU
	VCPU string `json:"vCPU,omitempty"`
}

// Validate validates this arc cost instance info
func (m *ArcCostInstanceInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc cost instance info based on context it is used
func (m *ArcCostInstanceInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostInstanceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostInstanceInfo) UnmarshalBinary(b []byte) error {
	var res ArcCostInstanceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
