// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostPathRequest arc cost path request
//
// swagger:model arc_cost_path_request
type ArcCostPathRequest struct {

	// avoid providers
	AvoidProviders []string `json:"avoidProviders"`

	// avoid regions
	AvoidRegions []string `json:"avoidRegions"`

	// destination cloud provider
	DestinationCloudProvider string `json:"destinationCloudProvider,omitempty"`

	// destination region
	DestinationRegion string `json:"destinationRegion,omitempty"`

	// max hops
	MaxHops uint8 `json:"maxHops,omitempty"`

	// required top paths
	RequiredTopPaths uint8 `json:"requiredTopPaths,omitempty"`

	// source cloud provider
	SourceCloudProvider string `json:"sourceCloudProvider,omitempty"`

	// source region
	SourceRegion string `json:"sourceRegion,omitempty"`
}

// Validate validates this arc cost path request
func (m *ArcCostPathRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc cost path request based on context it is used
func (m *ArcCostPathRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostPathRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostPathRequest) UnmarshalBinary(b []byte) error {
	var res ArcCostPathRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
