// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcOrchAPIKeyRequest arc orch api key request
//
// swagger:model arc_orch_api_key_request
type ArcOrchAPIKeyRequest struct {

	// expire date
	ExpireDate int64 `json:"expireDate,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this arc orch api key request
func (m *ArcOrchAPIKeyRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc orch api key request based on context it is used
func (m *ArcOrchAPIKeyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcOrchAPIKeyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcOrchAPIKeyRequest) UnmarshalBinary(b []byte) error {
	var res ArcOrchAPIKeyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
