// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostPathResponse arc cost path response
//
// swagger:model arc_cost_path_response
type ArcCostPathResponse struct {

	// destination region
	DestinationRegion string `json:"destinationRegion,omitempty"`

	// recommended paths
	RecommendedPaths []*ArcCostPath `json:"recommendedPaths"`

	// source region
	SourceRegion string `json:"sourceRegion,omitempty"`
}

// Validate validates this arc cost path response
func (m *ArcCostPathResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecommendedPaths(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostPathResponse) validateRecommendedPaths(formats strfmt.Registry) error {
	if swag.IsZero(m.RecommendedPaths) { // not required
		return nil
	}

	for i := 0; i < len(m.RecommendedPaths); i++ {
		if swag.IsZero(m.RecommendedPaths[i]) { // not required
			continue
		}

		if m.RecommendedPaths[i] != nil {
			if err := m.RecommendedPaths[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recommendedPaths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recommendedPaths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this arc cost path response based on the context it is used
func (m *ArcCostPathResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRecommendedPaths(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostPathResponse) contextValidateRecommendedPaths(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RecommendedPaths); i++ {

		if m.RecommendedPaths[i] != nil {
			if err := m.RecommendedPaths[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recommendedPaths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recommendedPaths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostPathResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostPathResponse) UnmarshalBinary(b []byte) error {
	var res ArcCostPathResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
