// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostPath arc cost path
//
// swagger:model arc_cost_path
type ArcCostPath struct {

	// path
	Path string `json:"path,omitempty"`

	// total cost
	TotalCost float64 `json:"totalCost,omitempty"`
}

// Validate validates this arc cost path
func (m *ArcCostPath) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc cost path based on context it is used
func (m *ArcCostPath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostPath) UnmarshalBinary(b []byte) error {
	var res ArcCostPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
