// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostPriceFunction arc cost price function
//
// swagger:model arc_cost_price_function
type ArcCostPriceFunction struct {

	// begin range
	BeginRange float64 `json:"beginRange,omitempty"`

	// currency code
	CurrencyCode string `json:"currencyCode,omitempty"`

	// end range
	EndRange float64 `json:"endRange,omitempty"`

	// price per unit
	PricePerUnit float64 `json:"pricePerUnit,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`
}

// Validate validates this arc cost price function
func (m *ArcCostPriceFunction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc cost price function based on context it is used
func (m *ArcCostPriceFunction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostPriceFunction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostPriceFunction) UnmarshalBinary(b []byte) error {
	var res ArcCostPriceFunction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
