// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostservicePathsRequest arc costservice paths request
//
// swagger:model arc_costservice_paths_request
type ArcCostservicePathsRequest struct {

	// avoid providers
	AvoidProviders []string `json:"avoidProviders"`

	// avoid regions
	AvoidRegions []string `json:"avoidRegions"`

	// destination cloud provider
	DestinationCloudProvider string `json:"destinationCloudProvider,omitempty"`

	// destination region
	DestinationRegion string `json:"destinationRegion,omitempty"`

	// max hops
	MaxHops int64 `json:"maxHops,omitempty"`

	// required top paths
	RequiredTopPaths int64 `json:"requiredTopPaths,omitempty"`

	// source cloud provider
	SourceCloudProvider string `json:"sourceCloudProvider,omitempty"`

	// source region
	SourceRegion string `json:"sourceRegion,omitempty"`
}

// Validate validates this arc costservice paths request
func (m *ArcCostservicePathsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc costservice paths request based on context it is used
func (m *ArcCostservicePathsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostservicePathsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostservicePathsRequest) UnmarshalBinary(b []byte) error {
	var res ArcCostservicePathsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
