// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostInterfaces arc cost interfaces
//
// swagger:model arc_cost_interfaces
type ArcCostInterfaces struct {

	// interface Id
	InterfaceID string `json:"interfaceId,omitempty"`

	// interface name
	InterfaceName string `json:"interfaceName,omitempty"`
}

// Validate validates this arc cost interfaces
func (m *ArcCostInterfaces) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this arc cost interfaces based on context it is used
func (m *ArcCostInterfaces) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostInterfaces) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostInterfaces) UnmarshalBinary(b []byte) error {
	var res ArcCostInterfaces
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
