// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostserviceCostmatrix arc costservice costmatrix
//
// swagger:model arc_costservice_costmatrix
type ArcCostserviceCostmatrix struct {

	// arc costservice costmatrix entries
	ArcCostserviceCostmatrixEntries []*ArcCostserviceCostmatrixEntry `json:"arc_costservice_costmatrix_entries"`
}

// Validate validates this arc costservice costmatrix
func (m *ArcCostserviceCostmatrix) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArcCostserviceCostmatrixEntries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostserviceCostmatrix) validateArcCostserviceCostmatrixEntries(formats strfmt.Registry) error {
	if swag.IsZero(m.ArcCostserviceCostmatrixEntries) { // not required
		return nil
	}

	for i := 0; i < len(m.ArcCostserviceCostmatrixEntries); i++ {
		if swag.IsZero(m.ArcCostserviceCostmatrixEntries[i]) { // not required
			continue
		}

		if m.ArcCostserviceCostmatrixEntries[i] != nil {
			if err := m.ArcCostserviceCostmatrixEntries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("arc_costservice_costmatrix_entries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("arc_costservice_costmatrix_entries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this arc costservice costmatrix based on the context it is used
func (m *ArcCostserviceCostmatrix) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArcCostserviceCostmatrixEntries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostserviceCostmatrix) contextValidateArcCostserviceCostmatrixEntries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ArcCostserviceCostmatrixEntries); i++ {

		if m.ArcCostserviceCostmatrixEntries[i] != nil {
			if err := m.ArcCostserviceCostmatrixEntries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("arc_costservice_costmatrix_entries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("arc_costservice_costmatrix_entries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostserviceCostmatrix) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostserviceCostmatrix) UnmarshalBinary(b []byte) error {
	var res ArcCostserviceCostmatrix
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
