// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArcCostVertex arc cost vertex
//
// swagger:model arc_cost_vertex
type ArcCostVertex struct {

	// ae
	Ae ArcedgeName `json:"ae,omitempty"`

	// deployment name
	DeploymentName string `json:"deployment_name,omitempty"`

	// interface name
	InterfaceName string `json:"interface_name,omitempty"`
}

// Validate validates this arc cost vertex
func (m *ArcCostVertex) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAe(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostVertex) validateAe(formats strfmt.Registry) error {
	if swag.IsZero(m.Ae) { // not required
		return nil
	}

	if err := m.Ae.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ae")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ae")
		}
		return err
	}

	return nil
}

// ContextValidate validate this arc cost vertex based on the context it is used
func (m *ArcCostVertex) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAe(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArcCostVertex) contextValidateAe(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Ae.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ae")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ae")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ArcCostVertex) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArcCostVertex) UnmarshalBinary(b []byte) error {
	var res ArcCostVertex
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
