// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AwsInstanceType aws instance type
//
// swagger:model aws_instance_type
type AwsInstanceType struct {

	// instance type
	InstanceType string `json:"instance_type,omitempty"`

	// maximum network interfaces
	MaximumNetworkInterfaces int64 `json:"maximum_network_interfaces,omitempty"`
}

// Validate validates this aws instance type
func (m *AwsInstanceType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this aws instance type based on context it is used
func (m *AwsInstanceType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AwsInstanceType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsInstanceType) UnmarshalBinary(b []byte) error {
	var res AwsInstanceType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
