// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AwsNetwork aws network
//
// swagger:model aws_network
type AwsNetwork struct {

	// name
	Name string `json:"name,omitempty"`

	// private subnet route table
	// Min Length: 1
	PrivateSubnetRouteTable string `json:"private_subnet_route_table,omitempty"`

	// subnet a
	SubnetA string `json:"subnetA,omitempty"`

	// subnet b
	SubnetB string `json:"subnetB,omitempty"`
}

// Validate validates this aws network
func (m *AwsNetwork) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrivateSubnetRouteTable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AwsNetwork) validatePrivateSubnetRouteTable(formats strfmt.Registry) error {
	if swag.IsZero(m.PrivateSubnetRouteTable) { // not required
		return nil
	}

	if err := validate.MinLength("private_subnet_route_table", "body", m.PrivateSubnetRouteTable, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this aws network based on context it is used
func (m *AwsNetwork) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AwsNetwork) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsNetwork) UnmarshalBinary(b []byte) error {
	var res AwsNetwork
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
