// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AwsCloudResourcesStateList aws cloud resources state list
//
// swagger:model aws_cloud_resources_state_list
type AwsCloudResourcesStateList struct {

	// amazon bgp address
	AmazonBgpAddress string `json:"amazon_bgp_address,omitempty"`

	// amazon side asn
	AmazonSideAsn string `json:"amazon_side_asn,omitempty"`

	// aws dx gateway
	AwsDxGateway string `json:"aws_dx_gateway,omitempty"`

	// aws dx gateway assocation
	AwsDxGatewayAssocation string `json:"aws_dx_gateway_assocation,omitempty"`

	// aws dx private virtual interface
	AwsDxPrivateVirtualInterface string `json:"aws_dx_private_virtual_interface,omitempty"`

	// aws route table
	AwsRouteTable string `json:"aws_route_table,omitempty"`

	// aws subnet
	AwsSubnet string `json:"aws_subnet,omitempty"`

	// aws vpc
	AwsVpc string `json:"aws_vpc,omitempty"`

	// aws vpn gateway
	AwsVpnGateway string `json:"aws_vpn_gateway,omitempty"`

	// aws vpn gateway route propagation
	AwsVpnGatewayRoutePropagation string `json:"aws_vpn_gateway_route_propagation,omitempty"`

	// customer bgp address
	CustomerBgpAddress string `json:"customer_bgp_address,omitempty"`

	// customer bgp asn
	CustomerBgpAsn string `json:"customer_bgp_asn,omitempty"`
}

// Validate validates this aws cloud resources state list
func (m *AwsCloudResourcesStateList) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this aws cloud resources state list based on context it is used
func (m *AwsCloudResourcesStateList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AwsCloudResourcesStateList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsCloudResourcesStateList) UnmarshalBinary(b []byte) error {
	var res AwsCloudResourcesStateList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
