// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AzureInterface azure interface
//
// swagger:model azure_interface
type AzureInterface struct {

	// interface id
	InterfaceID string `json:"interface_id,omitempty"`

	// route table name
	RouteTableName string `json:"route_table_name,omitempty"`
}

// Validate validates this azure interface
func (m *AzureInterface) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this azure interface based on context it is used
func (m *AzureInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureInterface) UnmarshalBinary(b []byte) error {
	var res AzureInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
