// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AzureInstanceType azure instance type
//
// swagger:model azure_instance_type
type AzureInstanceType struct {

	// accelerated networking enabled
	// Required: true
	AcceleratedNetworkingEnabled *bool `json:"accelerated_networking_enabled"`

	// maximum network interfaces
	MaximumNetworkInterfaces int64 `json:"maximum_network_interfaces,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this azure instance type
func (m *AzureInstanceType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAcceleratedNetworkingEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AzureInstanceType) validateAcceleratedNetworkingEnabled(formats strfmt.Registry) error {

	if err := validate.Required("accelerated_networking_enabled", "body", m.AcceleratedNetworkingEnabled); err != nil {
		return err
	}

	return nil
}

func (m *AzureInstanceType) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this azure instance type based on context it is used
func (m *AzureInstanceType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureInstanceType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureInstanceType) UnmarshalBinary(b []byte) error {
	var res AzureInstanceType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
