// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Connectionname connectionname
//
// swagger:model connectionname
type Connectionname string

// Validate validates this connectionname
func (m Connectionname) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this connectionname based on context it is used
func (m Connectionname) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
