// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Coordinates coordinates
//
// swagger:model coordinates
type Coordinates struct {

	// lat
	// Required: true
	Lat *float64 `json:"lat"`

	// long
	// Required: true
	Long *float64 `json:"long"`
}

// Validate validates this coordinates
func (m *Coordinates) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLong(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Coordinates) validateLat(formats strfmt.Registry) error {

	if err := validate.Required("lat", "body", m.Lat); err != nil {
		return err
	}

	return nil
}

func (m *Coordinates) validateLong(formats strfmt.Registry) error {

	if err := validate.Required("long", "body", m.Long); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this coordinates based on context it is used
func (m *Coordinates) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Coordinates) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Coordinates) UnmarshalBinary(b []byte) error {
	var res Coordinates
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
