// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Deploymentname deploymentname
//
// swagger:model deploymentname
type Deploymentname string

// Validate validates this deploymentname
func (m Deploymentname) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this deploymentname based on context it is used
func (m Deploymentname) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
