// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Dnsip dnsip
//
// swagger:model dnsip
type Dnsip string

// Validate validates this dnsip
func (m Dnsip) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dnsip based on context it is used
func (m Dnsip) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
