// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GcpOtherNetwork gcp other network
//
// swagger:model gcp_other_network
type GcpOtherNetwork struct {

	// network
	Network string `json:"network,omitempty"`

	// subnetwork
	Subnetwork string `json:"subnetwork,omitempty"`
}

// Validate validates this gcp other network
func (m *GcpOtherNetwork) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gcp other network based on context it is used
func (m *GcpOtherNetwork) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GcpOtherNetwork) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpOtherNetwork) UnmarshalBinary(b []byte) error {
	var res GcpOtherNetwork
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
