// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GcpDeployment gcp deployment
//
// swagger:model gcp_deployment
type GcpDeployment struct {

	// assign public ip
	AssignPublicIP bool `json:"assign_public_ip,omitempty"`

	// backup zone
	BackupZone string `json:"backup_zone,omitempty"`

	// byoip
	// Min Length: 1
	Byoip string `json:"byoip,omitempty"`

	// byoip backup
	// Min Length: 1
	ByoipBackup string `json:"byoip_backup,omitempty"`

	// instance key
	InstanceKey *InstanceKey `json:"instance_key,omitempty"`

	// instance type
	// Min Length: 1
	InstanceType string `json:"instance_type,omitempty"`

	// network tags
	NetworkTags []string `json:"network_tags"`

	// networks
	// Min Items: 1
	// Unique: true
	Networks []*GcpNetwork `json:"networks"`

	// region
	// Min Length: 1
	Region string `json:"region,omitempty"`

	// zone
	// Min Length: 1
	Zone string `json:"zone,omitempty"`
}

// Validate validates this gcp deployment
func (m *GcpDeployment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateByoip(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateByoipBackup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstanceKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstanceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateZone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GcpDeployment) validateByoip(formats strfmt.Registry) error {
	if swag.IsZero(m.Byoip) { // not required
		return nil
	}

	if err := validate.MinLength("byoip", "body", m.Byoip, 1); err != nil {
		return err
	}

	return nil
}

func (m *GcpDeployment) validateByoipBackup(formats strfmt.Registry) error {
	if swag.IsZero(m.ByoipBackup) { // not required
		return nil
	}

	if err := validate.MinLength("byoip_backup", "body", m.ByoipBackup, 1); err != nil {
		return err
	}

	return nil
}

func (m *GcpDeployment) validateInstanceKey(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceKey) { // not required
		return nil
	}

	if m.InstanceKey != nil {
		if err := m.InstanceKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instance_key")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instance_key")
			}
			return err
		}
	}

	return nil
}

func (m *GcpDeployment) validateInstanceType(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceType) { // not required
		return nil
	}

	if err := validate.MinLength("instance_type", "body", m.InstanceType, 1); err != nil {
		return err
	}

	return nil
}

func (m *GcpDeployment) validateNetworkTags(formats strfmt.Registry) error {
	if swag.IsZero(m.NetworkTags) { // not required
		return nil
	}

	for i := 0; i < len(m.NetworkTags); i++ {

		if err := validate.MinLength("network_tags"+"."+strconv.Itoa(i), "body", m.NetworkTags[i], 1); err != nil {
			return err
		}

		if err := validate.MaxLength("network_tags"+"."+strconv.Itoa(i), "body", m.NetworkTags[i], 63); err != nil {
			return err
		}

	}

	return nil
}

func (m *GcpDeployment) validateNetworks(formats strfmt.Registry) error {
	if swag.IsZero(m.Networks) { // not required
		return nil
	}

	iNetworksSize := int64(len(m.Networks))

	if err := validate.MinItems("networks", "body", iNetworksSize, 1); err != nil {
		return err
	}

	if err := validate.UniqueItems("networks", "body", m.Networks); err != nil {
		return err
	}

	for i := 0; i < len(m.Networks); i++ {
		if swag.IsZero(m.Networks[i]) { // not required
			continue
		}

		if m.Networks[i] != nil {
			if err := m.Networks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GcpDeployment) validateRegion(formats strfmt.Registry) error {
	if swag.IsZero(m.Region) { // not required
		return nil
	}

	if err := validate.MinLength("region", "body", m.Region, 1); err != nil {
		return err
	}

	return nil
}

func (m *GcpDeployment) validateZone(formats strfmt.Registry) error {
	if swag.IsZero(m.Zone) { // not required
		return nil
	}

	if err := validate.MinLength("zone", "body", m.Zone, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this gcp deployment based on the context it is used
func (m *GcpDeployment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInstanceKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetworks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GcpDeployment) contextValidateInstanceKey(ctx context.Context, formats strfmt.Registry) error {

	if m.InstanceKey != nil {
		if err := m.InstanceKey.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instance_key")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instance_key")
			}
			return err
		}
	}

	return nil
}

func (m *GcpDeployment) contextValidateNetworks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Networks); i++ {

		if m.Networks[i] != nil {
			if err := m.Networks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GcpDeployment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpDeployment) UnmarshalBinary(b []byte) error {
	var res GcpDeployment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
