// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GcpInstanceType gcp instance type
//
// swagger:model gcp_instance_type
type GcpInstanceType struct {

	// instance type
	InstanceType string `json:"instance_type,omitempty"`

	// v c p us
	VCPUs int64 `json:"vCPUs,omitempty"`

	// v n i cs
	VNICs int64 `json:"vNICs,omitempty"`
}

// Validate validates this gcp instance type
func (m *GcpInstanceType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gcp instance type based on context it is used
func (m *GcpInstanceType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GcpInstanceType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpInstanceType) UnmarshalBinary(b []byte) error {
	var res GcpInstanceType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
