// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IpsecPad ipsec pad
//
// swagger:model ipsec_pad
type IpsecPad struct {

	// ip address
	IPAddress string `json:"ip_address,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this ipsec pad
func (m *IpsecPad) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ipsec pad based on context it is used
func (m *IpsecPad) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IpsecPad) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpsecPad) UnmarshalBinary(b []byte) error {
	var res IpsecPad
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
