// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IpsecConn ipsec conn
//
// swagger:model ipsec_conn
type IpsecConn struct {

	// dh group
	DhGroup int64 `json:"dh_group,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// local ip
	LocalIP string `json:"local_ip,omitempty"`

	// local subnet
	LocalSubnet string `json:"local_subnet,omitempty"`

	// remote ip
	RemoteIP string `json:"remote_ip,omitempty"`

	// remote subnet
	RemoteSubnet string `json:"remote_subnet,omitempty"`

	// spd mark
	SpdMark int64 `json:"spd_mark,omitempty"`

	// spd name
	SpdName string `json:"spd_name,omitempty"`
}

// Validate validates this ipsec conn
func (m *IpsecConn) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ipsec conn based on context it is used
func (m *IpsecConn) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IpsecConn) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpsecConn) UnmarshalBinary(b []byte) error {
	var res IpsecConn
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
