// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KvmNetwork kvm network
//
// swagger:model kvm_network
type KvmNetwork struct {

	// name
	Name string `json:"name,omitempty"`

	// network
	Network string `json:"network,omitempty"`

	// private ip cidr mask
	PrivateIPCidrMask string `json:"private_ip_cidr_mask,omitempty"`

	// private ip default gw
	PrivateIPDefaultGw string `json:"private_ip_default_gw,omitempty"`
}

// Validate validates this kvm network
func (m *KvmNetwork) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kvm network based on context it is used
func (m *KvmNetwork) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KvmNetwork) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KvmNetwork) UnmarshalBinary(b []byte) error {
	var res KvmNetwork
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
