// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OciCompartment oci compartment
//
// swagger:model oci_compartment
type OciCompartment struct {

	// name
	Name string `json:"name,omitempty"`

	// ocid
	Ocid string `json:"ocid,omitempty"`
}

// Validate validates this oci compartment
func (m *OciCompartment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oci compartment based on context it is used
func (m *OciCompartment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OciCompartment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OciCompartment) UnmarshalBinary(b []byte) error {
	var res OciCompartment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
