// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OciAvailabilityDomain oci availability domain
//
// swagger:model oci_availability_domain
type OciAvailabilityDomain struct {

	// name
	Name string `json:"name,omitempty"`

	// ocid
	Ocid string `json:"ocid,omitempty"`
}

// Validate validates this oci availability domain
func (m *OciAvailabilityDomain) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oci availability domain based on context it is used
func (m *OciAvailabilityDomain) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OciAvailabilityDomain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OciAvailabilityDomain) UnmarshalBinary(b []byte) error {
	var res OciAvailabilityDomain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
