// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RestoreConfig restore config
//
// swagger:model restore_config
type RestoreConfig struct {

	// credentials
	// Required: true
	Credentials struct {
		AwsBackup

		OnpremBackup
	} `json:"credentials"`

	// filename
	// Required: true
	// Min Length: 1
	Filename *string `json:"filename"`

	// provider
	// Required: true
	Provider *string `json:"provider"`

	// use default
	// Required: true
	UseDefault *bool `json:"use_default"`
}

// Validate validates this restore config
func (m *RestoreConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCredentials(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilename(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUseDefault(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RestoreConfig) validateCredentials(formats strfmt.Registry) error {

	return nil
}

func (m *RestoreConfig) validateFilename(formats strfmt.Registry) error {

	if err := validate.Required("filename", "body", m.Filename); err != nil {
		return err
	}

	if err := validate.MinLength("filename", "body", *m.Filename, 1); err != nil {
		return err
	}

	return nil
}

func (m *RestoreConfig) validateProvider(formats strfmt.Registry) error {

	if err := validate.Required("provider", "body", m.Provider); err != nil {
		return err
	}

	return nil
}

func (m *RestoreConfig) validateUseDefault(formats strfmt.Registry) error {

	if err := validate.Required("use_default", "body", m.UseDefault); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this restore config based on the context it is used
func (m *RestoreConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCredentials(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RestoreConfig) contextValidateCredentials(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *RestoreConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestoreConfig) UnmarshalBinary(b []byte) error {
	var res RestoreConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
