// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SamlUsersResp saml users resp
//
// swagger:model saml_users_resp
type SamlUsersResp struct {

	// create
	Create []string `json:"create"`

	// edit
	Edit []string `json:"edit"`
}

// Validate validates this saml users resp
func (m *SamlUsersResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this saml users resp based on context it is used
func (m *SamlUsersResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SamlUsersResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SamlUsersResp) UnmarshalBinary(b []byte) error {
	var res SamlUsersResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
