// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TerraformResource terraform resource
//
// swagger:model terraform_resource
type TerraformResource struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// state
	State bool `json:"state,omitempty"`
}

// Validate validates this terraform resource
func (m *TerraformResource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this terraform resource based on context it is used
func (m *TerraformResource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TerraformResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TerraformResource) UnmarshalBinary(b []byte) error {
	var res TerraformResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
